### ISSUE TITLE
TagsInputComponent.html:20 ERROR TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by adrienblin** [Sonaryr/ngx-tags-input#1]
Hello, my angular app using ng tas input crash at boot on this line:

https://github.com/Sonaryr/ng2-tags-input/blob/8816f83e3d3b5710876c7363712c54eaaf531502/src/tags-input.component.ts#L110

here is the html:
```html
Alerts :
<tags-input class="form-control"
            [removeLastOnBackspace]="true"
            [(ngModel)]="alertsSelectedNames"
            placeholder="Select an alert"
            (onTagsChanged)="onTagsChanged($event)"
            [options]="alertsDisplayNames"></tags-input>
```

here is the stack trace:
```
 TypeError: Cannot read property 'length' of null
    at TagsInputComponent.webpackJsonp.../../../../ng2-tags-input/dist/src/tags-input.component.js.TagsInputComponent.getPlaceHolder
```

**Comment by Sonaryr** [comment]
@adrienblin can you also post an extract of your Component code?

**Comment by adrienblin** [comment]
Here is my component : 
```javascript
import {Component, EventEmitter, OnInit, Output} from '@angular/core';

@Component({
  selector: 'alert-selector',
  templateUrl: './alert-selector.component.html',
  styleUrls: ['./alert-selector.component.css']
})

export class AlertSelectorComponent implements OnInit {
  alerts: Alert[] = [];
  selectedAlertsNames: any[] = [{displayValue: 'All'}];
  selectableAlertNames: String[] = [];
  public selectedAlerts = ['all'];
  @Output()
  onAlertSelected: EventEmitter<any> = new EventEmitter();

  constructor() {
  }

  ngOnInit() {
    // Fetching alerts here
  }

  onTagsChanged(event) {
    switch (event.change) {
      case 'add':
        //Handling add of alerts
      case 'remove':
       //Handling deletion of alerts
    }
  }
}
```
Regards.

**Comment by Sonaryr** [comment]
@adrienblin 
your ngModel does not exist on your component. If you alter this it should work.

**Comment by RodolpheGohard** [comment]
Hello, I confirm this bug, and it comes down from a bug in angular itself it seems:
https://github.com/angular/angular/issues/14988

For some reason, angular will call writeValue() with a null a first time, then call writeValue() a second time with the correct initial Value.

The bug is still open, but there is this not-that-nice workaround:
> because FormControl is initialized with null value. Just add a check if (obj != null) {}
