### ISSUE TITLE
Number of options in dropdown

### ISSUE THREAD

**Issue by adrienblin** [Sonaryr/ngx-tags-input#12]
Hello,

I was wondering if you could add an attribute where you could chose the number of options in the dropdown. It seems that for the moment, the value is the default one in the ngx-bootstrap typeahead directive, which is 20.

Thank you very much in advance.

**Comment by acipher** [comment]
+1

**Comment by Sonaryr** [comment]
There is an option for that `scrollableOptionsInView`
