### ISSUE TITLE
Show all available options on click

### ISSUE THREAD

**Issue by adrienblin** [Sonaryr/ngx-tags-input#2]
Hello,

I'm coming back to you again with a question/feature request. When you click on the component, without typing anything, is it possible to display all available options on the dropdown ? Because when a user doesn't know what are the available options to the field, he doesn't know what to look for, so it can feel not user-friendly.

I looked through the readme and didn't see a way to do this right now.

Many thanks !

**Comment by Sonaryr** [comment]
Hi, at the moment this is not available indeed, I will try to have a look at it tomorrow.

**Comment by adrienblin** [comment]
Great, thank you very much !

**Comment by Sonaryr** [comment]
I've added to options to choose at what length you want to show the dropdown, selecting 0 will show it on focus (in v1.1.0).
README is updated to reflect the changes.
