### ISSUE TITLE
tag-input is not known element

### ISSUE THREAD

**Issue by abyesarah** [Sonaryr/ngx-tags-input#3]
Uncaught (in promise): Error: Template parse errors:
'tags-input' is not a known element:
1. If 'tags-input' is an Angular component, then verify that it is part of this module.
2. If 'tags-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<tags-input class="form-control input-lg" [(ngModel)]="tags" name="tags"></tags-input>

**Comment by Sonaryr** [comment]
can you add some more context? As in your html, your module,...

**Comment by abyesarah** [comment]
......
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import {MenuRoutingModule} from './menu-routing.module';
import { TagsInputModule } from 'ngx-tags-input/dist';


@NgModule({
  imports: [
    MenuRoutingModule,
    ChartsModule,
    BsDropdownModule,
    TagsInputModule.forRoot()


  ],

  declarations: [ MenuComponent ]
})
export class MenuModule { }
this is the main module

**Comment by abyesarah** [comment]
<tags-input class="form-control input-lg" (onTagsChanged)="onTagsChanged($event)" [(ngModel)]="tags" name="tags"></tags-input>

...
this is the line that gives me error

**Comment by Sonaryr** [comment]
And do you use it in the same module as you import it?

**Comment by abyesarah** [comment]
yes but still it gives this element not known error

**Comment by RetGal** [comment]
Same issue here @angular 4.3

**Comment by Sonaryr** [comment]
After testing and a lot of people are already using it and it is working I'm closing this one
