### ISSUE TITLE
Tags in null so can't find length property

### ISSUE THREAD

**Issue by musmanpak** [Sonaryr/ngx-tags-input#4]
I'm making it tags an array and some is my ngModel assigned to it. But it stays, 'length' property undefined of null (which is this.tags is null).

**Comment by Mattek1979** [comment]
I'm having the same problem.  Seems like the method
`private getPlaceHolder(): string {
        if(this.tags.length > 0){
            return '';
        }
        return this.placeholder;
 }`

in TagsInputComponent should be something like

`private getPlaceHolder(): string {
        if(this.tags && this.tags.length > 0){
            return '';
        }
        return this.placeholder;
 }`

instead. There seems to be some kind of problem with scope maybe.

**Comment by mikehoh** [comment]
I have the same problem.

@Mattek1979 Your solution works. 
But we need it in repository.

**Comment by Sonaryr** [comment]
Sorry, was on holiday. will publish the fix tomorrow to npm, but please do feel free to create a pull request already

**Comment by Sonaryr** [comment]
fixed in v1.1.1

**Comment by mikehoh** [comment]
@Sonaryr Thanks!

**Comment by Mattek1979** [comment]
Thanks, didn't have time to create a pull request
