### ISSUE TITLE
Can't read the right value with Angular 5 

### ISSUE THREAD

**Issue by cloudmelon** [Sonaryr/ngx-tags-input#8]
I used this component but it seems that it can't display the right value for array in javascript:
![image](https://user-images.githubusercontent.com/4621560/37840440-5f47a51a-2ebd-11e8-85c2-fcccfd3b0d43.png)

![image](https://user-images.githubusercontent.com/4621560/37840458-6b48be6c-2ebd-11e8-9021-e070b09809e3.png)

No error in console.

**Comment by Sonaryr** [comment]
At the moment the library requires an array of objects, so just an array of strings won't work
