### ISSUE TITLE
Tags in null so can't find length property 

### ISSUE THREAD

**Issue by Hardik-Vibe** [Sonaryr/ngx-tags-input#9]
I am getting an error in 'maximumOfTagsReached' method that 'can't find length property' as Tags values are null.

I have noticed that when we create component it executes writeValue method two times one with null values and the second time with actual data. I guess the first call of writeValue with null data is causing this issue.

We can quick fix as previously did for placeholder method. You can get the reference from here: - https://github.com/Sonaryr/ngx-tags-input/blob/master/src/tags-input.component.ts

Let me know if any query. In meantime, I'll create the pull request for same with the quick fix.

**Comment by Sonaryr** [comment]
Should be fixed in v2.0.0
